import { useState } from 'react'
import type { AuditLog } from '../api/types'
import { MagnifyingGlassIcon } from '@heroicons/react/24/outline'
import DataTable from '../components/ui/DataTable'
import type { Column } from '../components/ui/DataTable'
import ErrorAlert from '../components/ui/ErrorAlert'
import Pagination from '../components/ui/Pagination'
import { useQuery } from '@tanstack/react-query'
import * as auditLogsApi from '../api/auditLogs'

const columns: Column<AuditLog>[] = [
  { key: 'id', header: 'ID' },
  { key: 'entity_type', header: 'Entity Type' },
  { key: 'entity_id', header: 'Entity ID' },
  { key: 'action', header: 'Action', render: (item) => (
    <span className={`inline-flex items-center rounded-full px-2 py-1 text-xs font-medium ${
      item.action === 'create' ? 'bg-green-100 text-green-700' :
      item.action === 'update' ? 'bg-blue-100 text-blue-700' :
      item.action === 'delete' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-700'
    }`}>
      {item.action}
    </span>
  )},
  { key: 'changes', header: 'Changes', render: (item) => (
    <span className="text-xs font-mono truncate max-w-xs block" title={JSON.stringify(item.changes)}>
      {item.changes ? JSON.stringify(item.changes) : '-'}
    </span>
  )},
  { key: 'user_email', header: 'User' },
  { key: 'ip_address', header: 'IP Address' },
  { key: 'created_at', header: 'Created At', render: (item) => new Date(item.created_at).toLocaleString() },
]

export default function AuditLogsPage() {
  const [search, setSearch] = useState('')
  const [offset, setOffset] = useState(0)
  const [entityTypeFilter, setEntityTypeFilter] = useState<string>('')
  const [actionFilter, setActionFilter] = useState<string>('')
  const [userEmailFilter, setUserEmailFilter] = useState<string>('')
  const limit = 50

  const { data, isLoading, error } = useQuery({
    queryKey: ['audit-logs', { 
      search: search || undefined,
      entity_type: entityTypeFilter || undefined, 
      action: actionFilter || undefined,
      user_email: userEmailFilter || undefined,
      limit, 
      offset 
    }],
    queryFn: () => auditLogsApi.getAll({ 
      search: search || undefined,
      entity_type: entityTypeFilter || undefined, 
      action: actionFilter || undefined,
      user_email: userEmailFilter || undefined,
      limit, 
      offset 
    })
  })

  if (error) return <ErrorAlert message={error.message} />

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-bold text-gray-900">Audit Logs</h1>
          {data?.count != null && (
            <span className="rounded-full bg-gray-200 px-2.5 py-0.5 text-xs font-medium text-gray-700">
              {data.count}
            </span>
          )}
        </div>
      </div>

      <div className="mb-4 bg-blue-50 border border-blue-200 rounded-lg px-4 py-3">
        <p className="text-sm text-blue-800">
          <strong>Read-only:</strong> Audit logs cannot be created, edited, or deleted. They are automatically generated by the system.
        </p>
      </div>

      <div className="mb-4 flex gap-3">
        <div className="relative flex-1">
          <MagnifyingGlassIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
          <input type="text" value={search}
            onChange={(e) => { setSearch(e.target.value); setOffset(0) }}
            placeholder="Search logs..."
            className="w-full rounded-lg border border-gray-300 pl-9 pr-3 py-2 text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
        </div>
        <input type="text" value={entityTypeFilter}
          onChange={(e) => { setEntityTypeFilter(e.target.value); setOffset(0) }}
          placeholder="Entity type"
          className="w-40 rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
        <select value={actionFilter} onChange={(e) => { setActionFilter(e.target.value); setOffset(0) }}
          className="rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500">
          <option value="">All Actions</option>
          <option value="create">Create</option>
          <option value="update">Update</option>
          <option value="delete">Delete</option>
        </select>
        <input type="text" value={userEmailFilter}
          onChange={(e) => { setUserEmailFilter(e.target.value); setOffset(0) }}
          placeholder="User email"
          className="w-48 rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
      </div>

      <DataTable
        columns={columns}
        data={data?.data ?? []}
        isLoading={isLoading}
      />

      {data && data.count > limit && (
        <Pagination
          offset={offset}
          limit={limit}
          total={data.count}
          onPageChange={setOffset}
        />
      )}
    </div>
  )
}
